#pragma once

#include <unordered_map>
#include <string>
#include "utils/token.hpp"
#include "bytecodes.hpp"
#include "values/value.hpp"
#include "values/u32.hpp"
#include "nodes/literal.hpp"
#include "utils/func_info.hpp"

namespace utils {
    inline constexpr const char *BUILTIN_PACKAGE = "APICA";

    inline constexpr std::string_view APIC_HELP = R"(usage: apic <command> [options]

commands:
    init        initialize a basic apica workdir with assets folder, sources folder and main source file
    build       build a bytecode file (.apb) from a main apica source file (.apc)
    help        display this information
    version     display the version number of apic

options: [i(nit) | b(uild)]
    [b]     -i <path>   provide a path to the main apica source file
    [b]     -o <path>   provide an output path to the generated bytecode file
    [b]     --nodes     show the produced bode tree
    [b]     --no-opt    disable optimizations
)";

    static const std::unordered_map<std::string, TokenKind> APICA_KEYWORDS = {
        {"var", TokenKind::Var},
        {"const", TokenKind::Const},
        {"func", TokenKind::Func},
        {"lambda", TokenKind::Lambda},

        {"if", TokenKind::If},
        {"else", TokenKind::Else},
        {"while", TokenKind::While},

        {"break", TokenKind::Break},
        {"continue", TokenKind::Continue},
        {"return", TokenKind::Return},

        {"true", TokenKind::True},
        {"false", TokenKind::False},
        {"null", TokenKind::Null},

        {"entry", TokenKind::Entrypoint},
        {"specs", TokenKind::Specifications},

        {"global", TokenKind::Global},

        {"as", TokenKind::As},
        {"typeof", TokenKind::Typeof}
    };

    static const std::unordered_map<std::string, common::bytecodes::ApicaTypeBytecode> APICA_TYPES = {
        {"any", common::bytecodes::ApicaTypeBytecode::Any},

        {"i8", common::bytecodes::ApicaTypeBytecode::I8},
        {"i16", common::bytecodes::ApicaTypeBytecode::I16},
        {"i32", common::bytecodes::ApicaTypeBytecode::I32},
        {"i64", common::bytecodes::ApicaTypeBytecode::I64},
        {"u8", common::bytecodes::ApicaTypeBytecode::U8},
        {"u16", common::bytecodes::ApicaTypeBytecode::U16},
        {"u32", common::bytecodes::ApicaTypeBytecode::U32},
        {"u64", common::bytecodes::ApicaTypeBytecode::U64},

        {"f32", common::bytecodes::ApicaTypeBytecode::F32},
        {"f64", common::bytecodes::ApicaTypeBytecode::F64},

        {"bool", common::bytecodes::ApicaTypeBytecode::Bool},

        {"char", common::bytecodes::ApicaTypeBytecode::Char},
        {"string", common::bytecodes::ApicaTypeBytecode::String},

        {"error", common::bytecodes::ApicaTypeBytecode::Error},
        {"type", common::bytecodes::ApicaTypeBytecode::Type}
    };

    static const std::unordered_map<std::string, nodes::NodeLiteral> APICA_CONSTANTS = [] {
        std::unordered_map<std::string, nodes::NodeLiteral> m;

        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_Q"),
            std::forward_as_tuple(new common::values::ValueU32(20))
        );
        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_W"),
            std::forward_as_tuple(new common::values::ValueU32(26))
        );
        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_E"),
            std::forward_as_tuple(new common::values::ValueU32(8))
        );
        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_R"),
            std::forward_as_tuple(new common::values::ValueU32(21))
        );
        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_T"),
            std::forward_as_tuple(new common::values::ValueU32(23))
        );
        m.emplace(
            std::piecewise_construct,
            std::forward_as_tuple("KEY_Y"),
            std::forward_as_tuple(new common::values::ValueU32(28))
        );

        return m;
    }();

    static const std::unordered_map<std::string, common::bytecodes::ApicaSpecificationBytecode> APICA_SPECIFICATIONS = {
        {"title", common::bytecodes::ApicaSpecificationBytecode::Title},
        {"id", common::bytecodes::ApicaSpecificationBytecode::Id},
        {"logger", common::bytecodes::ApicaSpecificationBytecode::LoggerActivation},
        {"width", common::bytecodes::ApicaSpecificationBytecode::WindowWidth},
        {"height", common::bytecodes::ApicaSpecificationBytecode::WindowHeight},
        {"version", common::bytecodes::ApicaSpecificationBytecode::Version}  
    };

    static const std::unordered_map<std::string, BuiltinFunctionInfo> APICA_BUILTIN_FUNCTIONS = {
        {"Quit", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::QuitApp,
            {}
        )},

        {"LoadApp", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LoadApp,
            {
                ParameterInfo(false)
            }
        )},

        {"LogInfo", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LogInfo,
            {
                ParameterInfo(true)
            }
        )},

        {"LognInfo", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LognInfo,
            {
                ParameterInfo(true)
            }
        )},

        {"LogSuccess", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LogSuccess,
            {
                ParameterInfo(true)
            }
        )},

        {"LognSuccess", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LognSuccess,
            {
                ParameterInfo(true)
            }
        )},

        {"LogWarning", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LogWarning,
            {
                ParameterInfo(true)
            }
        )},

        {"LognWarning", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LognWarning,
            {
                ParameterInfo(true)
            }
        )},

        {"LogError", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LogError,
            {
                ParameterInfo(true)
            }
        )},

        {"LognError", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::LognError,
            {
                ParameterInfo(true)
            }
        )},

        {"SetTitle", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::SetTitle,
            {
                ParameterInfo(false)
            }
        )},

        {"SetResizable", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::SetResizable,
            {
                ParameterInfo(false)
            }
        )},

        {"IsKeyReleased", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::IsKeyReleased,
            {
                ParameterInfo(false)
            }
        )},

        {"IsKeyJustPressed", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::IsKeyJustPressed,
            {
                ParameterInfo(false)
            }
        )},

        {"IsKeyPressed", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::IsKeyPressed,
            {
                ParameterInfo(false)
            }
        )},

        {"IsKeyJustReleased", BuiltinFunctionInfo(
            common::bytecodes::ApicaBuiltinFunctionBytecode::IsKeyJustReleased,
            {
                ParameterInfo(false)
            }
        )}
    };
}