use std::fs::{create_dir, read_to_string, File};
use std::io::Write;
use std::path::Path;
use crate::core::analyzer::Analyzer;
use crate::core::emitter::Emitter;
use crate::core::options::{ApicOption, OptionKind};
use crate::core::parser::Parser;
use crate::utils::diagnostic_bag::DiagnosticBag;
use crate::utils::source::SourceText;

pub fn init_apic_workdir() {
    if create_dir("assets").is_err() {
        println!("\x1b[31mapic error: failed to create assets directory\x1b[0m");
    }

    if create_dir("src").is_err() {
        println!("\x1b[31mapic error: failed to create sources directory\x1b[0m");
    }

    let main_path = Path::new("src/main.apc");
    if !main_path.exists() {
        let main_file = File::create("src/main.apc");
        if let Ok(mut file) = main_file {
            if file.write_all(b"// Basic apica main file - automatically generated\n\nentry init {}\n\nentry update {}\n\nentry quit {}\n").is_err() {
                println!("\x1b[31mapic error: failed to write main apica source file\x1b[0m");
            }
        } else {
            println!("\x1b[31mapic error: failed to create main apica source file\x1b[0m");
        }
    }
}

pub fn show_apic_help() {
    println!(r#"usage: apic <command> [options]

commands:
    init        initialize a basic apica workdir with assets folder, sources folder and main file
    build       build a bytecode file (.apb) from a main apica source file (.apc)
    help        display this information
    version     display the version number of apic

options: [i(nit)|b(uild)|h(elp)|v(ersion)]
    [b]     -i <path>   provide a path to the main apica source file
    [b]     -o <path>   provide an output path to the generated bytecode file"#);
}

pub fn build_bytecode_file(options: &Vec<ApicOption>) -> bool {
    let mut diag_bag = DiagnosticBag::init();

    let mut input_filepath: Option<String> = None;
    let mut output_filepath = String::new();
    for option in options {
        if *option.get_kind() == OptionKind::SourceFile {
            if input_filepath.is_some() {
                println!("\x1b[31mapic error: cannot specify more than one main apica source file (i.e. -i)\x1b[0m");
                return false;
            } else {
                input_filepath = Some(option.get_value().clone());
            }
        } else if *option.get_kind() == OptionKind::OutputFile {
            if !output_filepath.is_empty() {
                println!("\x1b[31mapic error: cannot specify more than one output filepath (i.e. -o)\x1b[0m");
                return false;
            } else {
                output_filepath = option.get_value().clone();
            }
        }
    }

    if input_filepath.is_none() {
        println!("\x1b[31mapic error: `build` command needs a specified main apica source file (i.e. -i)\x1b[0m");
        return false;
    }
    
    if output_filepath.is_empty() {
        output_filepath = String::from("out.apb");
    }
    

    // Read the input source file
    let content = read_to_string(&input_filepath.unwrap());
    if content.is_err() {
        println!("\x1b[31mapic error: failed to read the content of main apica source file\x1b[0m");
        return false;
    }
    
    let content_string = content.unwrap().trim_start_matches("\u{feff}").to_string().replace("\r\n", "\n");
    let source = SourceText::init(content_string);
    
    
    // Build the AST
    let mut parser = Parser::init(&mut diag_bag, &source);
    let mut root = parser.parse();

    
    // Analyze and emit the AST
    let mut analyzer = Analyzer::init(&mut diag_bag);
    analyzer.analyze(&mut root);
    if let Some(mut emitter) = Emitter::init(&mut diag_bag, &output_filepath) {
        emitter.emit(&mut root);
    }
    
    
    // Show diagnostics and return
    root.show(&mut String::new(), '\n');
    diag_bag.show_all(&source);
    !diag_bag.has_any_error()
}